server {
    listen 80;
    server_name www.traektoria51.ru traektoria51.ru;

    root /var/www/static/landing;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

